version: '3'

services:
  api-imagegallery-client-webapi:
    container_name: 'api-imagegallery-client-webapi'
    image: stuartshay/imagegallery-api-client:2.1.0-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - 9150:8150
      - 4333:3333
