{
 "title": "ps-monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Customer Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(HomePage_ActiveSessions) without (host, instance, job)"
    }
   ]
  },
  {
   "title": "Customer Orders",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(HomePage_SessionStatus{status=\"checked-out\"}) without (host, instance, job)"
    }
   ]
  },
  {
   "title": "Cart Items",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(HomePage_SessionStatus{status=\"added-to-cart\"}) without (host, instance, job)"
    }
   ]
  },
  {
   "title": "Management Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(HomePage_ActiveSessions) without (host, instance, job)"
    }
   ]
  },
  {
   "title": "Stock Orders",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(StockManagement_SessionStatus{status=\"order-submitted\"}) without (host, instance, job)"
    }
   ]
  },
  { "title": "Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "IIS Requests/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(w3svc_w3wp_requests_per_sec[12h])) without(host, instance, job, exported_instance)"
    }
   ]
  },
  {
   "title": ".NET Thread Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_thread_count" }
   ]
  },
  {
   "title": ".NET Heap Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dotnet_clr_memory_gen_0_heap_size) without(host, instance, job, exported_instance)"
    }
   ]
  },
  {
   "title": "Tomcat Requests/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tomcat_requestprocessor_request_count{name=\"http-nio-8080\"}[12h])) without (host, instance, job)"
    }
   ]
  },
  {
   "title": "JVM Heap Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{area=\"heap\"}) without(instance, job)"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Docker Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Nodes Online",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(swarm_manager_nodes{state=\"ready\"})"
    }
   ]
  },
  {
   "title": "Container States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(engine_daemon_container_states_containers) without(instance, job)"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(engine_daemon_container_states_containers{state=\"running\"}) without (job, state)"
    }
   ]
  },
  {
   "title": "Failed Healthchecks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(engine_daemon_health_checks_failed_total) without(job)"
    }
   ]
  },
  {
   "title": "Nodes Offline",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(swarm_manager_nodes{state!=\"ready\"})"
    }
   ]
  }
 ]
}